# Additional Background

## Package Installation

There is a great blog post that provides useful background on package installation from different sources.
If you have 10 minutes, it is recommended to go through the [post by Thomas Neitmann](https://thomasadventure.blog/posts/install-r-packages/).

### Installing from CRAN

The R mothership repository for packages is [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/).

With `install.packages("ggplot2")` you will install the (latest released version of) {ggplot2} package and all its dependencies.
Thus, be prepared that a package installation may result in several other packages to be installed as well.

You can install multiple packages by providing them as a vector of package names using the c() function.
For example, `install.packages(c("ggplot2", "ggmap", "dlyr"))` will install {ggplot2}, {ggmpap}, and {dplyr}, as well the dependent packages if applicable.

### Installing from Github with {remotes}

While CRAN is the mothership, many packages are developed and hosted on github. 
In particular, if you interested in evaluating a most recent development version of a packages, it is a good guess that this version is available on github.

Before you can install any package from GitHub, you need to install the {remotes} package from CRAN, i.e. `install.packages("remotes")`.

{remotes} supports the download of packages from GitHub by providing *"username/repository"* as argument to remotes::install_github().
For example, the latest development version of {ggplot2} from GitHub can be downloaded with `remotes::install_github("tidyverse/ggplot2")`

If you download from GitHub, you are downloading and installing it from *source*.

The {remotes} package supports also the download from other repositories, e.g. gitlab, bitbucket, etc. If you know what these repositories are, you can check for the respective install function from the {remotes} package.

### Installing Binaries or from Source

The install.packages() function has a type parameter that controls whether a package is installed from pre-complied binaries or from source. 
The former is the default on Windows, thus we are safe on EUROCONTROL computers. Other operating systems require a proper development environment. 

Pre-compiled binaries have been developed on a computer with your operating system.
Thus, there is some testing, and the packages will load faster (as they do not have to be "built").

By default stay away from installing source.
When you answer *no* R will attempt to install the previous binary version of the package.

### Package Directory

With the function `.libPaths()` you can check the path to which your packages will be loaded/installed.

If you want to keep your installed packages in a specific path (or directory), you can provide the installation path to `install.packages()`. 
Check the help packages is unsure what to do.

On EUROCONTROL computers, the read/write restrictions require the download of packages to a subfolder of `\C:\Users\<your-user-name>\dev`. You should find a subfolder `R\win-library\<R-version-number>`.
No need to remember this. This should be set through the IT installation of R/RStudio.
