--- 
title: "Getting Started with R/RStudio"
author: "PRU"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: https://github.com/rainer-rq-koelle/pru-learnR-booklet
description: "This booklet comprises the working material for getting started with R/RStudio. It reflects the hacking sessions of PRU members"
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Welcome {-}

This booklet is produced in parallel to the *joint hacking sessions* and serves as an aide memoire.

Each (learning) journey starts with the first steps. 
And learning R, RStudio, the many useful R packages combine for a universe that is impossible to explore in a single go.

Thus, the goal is to get you started and give you some orientation on how to navigate this universe.

The booklet is not an invention of the author. It uses the feedback from several runs of the "getting started" (intro to R/RStudio) sessions.
And it lives from the feedback, observations, and the many *ahas* we had while hacking and learning together.

If you find this resource useful, feel free to reuse it!
If you find mistakes or have ideas to improve the presentation/wording, please reach out to us.

The R/RStudio ecosystem is a living organism and will change over time. 
Keep in mind the date of this resource.


